---
name: ShiftLeft
on:
  push:
    branches:
      - main
      - master
  pull_request: null
  workflow_dispatch: null
jobs:
  NextGen-Static-Analyis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download ShiftLeft CLI
        run: >
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod
          a+rx ${GITHUB_WORKSPACE}/sl
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: NextGen Static Analysis
        run: ${GITHUB_WORKSPACE}/sl analyze --wait --verbose --app Demo-java --tag
          branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
      - name: Validate Build Rules
        run: >
          ${GITHUB_WORKSPACE}/sl check-analysis --v2 --app Demo-java --config
          ~/shiftleft.yml\
             --report \
            --github-pr-number=${{github.event.number}} \
              --github-pr-user=${{ github.repository_owner }} \
              --github-pr-repo=${{ github.event.repository.name }} \
              --github-token=${{ secrets.GITHUB_TOKEN }}
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
